  zabbix_front:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix_front
    environment:
       - MYSQL_USER=zabbix
       - MYSQL_PASSWORD=Passw0rd   
       - MYSQL_DATABASE=zabbix
       - MYSQL_ROOT_PASSWORD=Passw0rd
    links:
       - zabbix_db
       - zabbix_server
    depends_on:
       - zabbix_db
       - zabbix_server
    volumes:
       - /etc/localtime:/etc/localtime:ro
    ports:
       - "90:8080"
    env_file:
       - ./services/zabbix/zabbix_front.env
#MYSQL_DATABASE="zabbix_db"
    restart: unless-stopped

  zabbix_db:
    image: yobasystems/alpine-mariadb
    container_name: zabbix_db
    env_file:
      - ./services/zabbix/zabbix_db.env
    volumes:
      - ./volumes/zabbix/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  zabbix_server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix_server 
    volumes:
      - ./volumes/zabbix/alertscripts/:/usr/lib/zabbix/alertscripts 
      - ./volumes/zabbix/externalscripts:/usr/lib/zabbix/externalscripts 
      - ./volumes/zabbix/snmptraps/:/var/lib/zabbix/snmptraps 
      - ./volumes/zabbix/mibs/:/var/lib/zabbix/mibs 
      - ./volumes/zabbix/alerta.log:/usr/lib/zabbix/alerta.log 
      - /etc/localtime:/etc/localtime:ro 
    env_file:
      - ./services/zabbix/zabbix_server.env
      # -e ZBX_VMWARECACHESIZE=8M 
    links:
       - zabbix_db
    ports:
      - "10051:10051"
      - "10050:10050"
    restart: unless-stopped 
